
package ventanas;
import java.sql.*;
import clases.Conexion;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;
public class Gestionar_Equipos extends javax.swing.JFrame {
    String user;
    public static int ID_equipo_update = 0;// usamos para comunicar
    DefaultTableModel model = new DefaultTableModel();

    
    public Gestionar_Equipos() {
        initComponents();
        user = Login.user;
        setSize(501, 450);
        setResizable(false);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Atencion al publico- sesion de " + user);
   try{
       Connection cn =Conexion.conectar();
       PreparedStatement pst = cn.prepareStatement(
       "select ID_equipo, tipo_equipo, marca, estatus from equipos");
      ResultSet rs = pst.executeQuery();
      table_equipos = new JTable(model);
      Scroll_equipos.setViewportView(table_equipos) ;
      
      model.addColumn("");
      model.addColumn("tipo");
      model.addColumn("marca");
      model.addColumn("estatus");
     
    
      
      while(rs.next()){
          Object [] fila = new Object [4];
          for ( int i = 0 ; i<4; i++){
              fila[i]= rs.getObject(i+1); 
              
          }
          model.addRow(fila);
          
      }
      
      cn.close();
       
   }catch(SQLException e ){
       System.err.println("error en llenado" + e);
       JOptionPane.showMessageDialog( null, " error, contacte" );
       
       
   }
   ObtenerMetodos();
   
    
    //eventos para el click
    
    
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Scroll_equipos = new javax.swing.JScrollPane();
        table_equipos = new javax.swing.JTable();
        combo_status = new javax.swing.JComboBox<>();
        buscar = new javax.swing.JToggleButton();
        wlp = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Equipos Registrados");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 130, -1));

        table_equipos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Scroll_equipos.setViewportView(table_equipos);

        getContentPane().add(Scroll_equipos, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, 200));

        combo_status.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "todos", "nuevo ingreso", "no reparado", "reparado", "entregado", " " }));
        getContentPane().add(combo_status, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, 100, -1));

        buscar.setText("Buscar");
        buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarActionPerformed(evt);
            }
        });
        getContentPane().add(buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 280, 130, 50));

        wlp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/wp-1.jpg"))); // NOI18N
        getContentPane().add(wlp, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarActionPerformed
        String seleccion= combo_status.getSelectedItem().toString();
        String query = "";
        // hay que limpiar la tabla cada vez que sea presiondado el boton.
        model.setRowCount(0);
        model.setColumnCount(0);
        try{
            Connection cn = Conexion.conectar();// las instrucciones van a ser dinamicas dependienro del buscador.
            if(seleccion.equals("todos")){
            query="select id_equipo, tipo_equipo, marca, estatus from equipos";
            }else{
             query="select id_equipo, tipo_equipo, marca, estatus from equipos where estatus='" + seleccion +"'";       
                    }
            
            PreparedStatement pst = cn.prepareStatement(query);
            ResultSet rs= pst.executeQuery();
            table_equipos= new JTable(model);
            Scroll_equipos.setViewportView(table_equipos);
            model.addColumn(" ");
            model.addColumn("tipo");
            model.addColumn("marca");
            model.addColumn("status");
            while(rs.next()){
                Object[] fila = new Object[4];
                for(int i=0; i<4;i++){
                    fila[i]= rs.getObject(i+1);
                    
                }
                model.addRow(fila);
            }
            cn.close();
        }catch(SQLException e){
            System.err.println("error en tabla equipos" + e);
        }
        ObtenerMetodos();
        
        
    }//GEN-LAST:event_buscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gestionar_Equipos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gestionar_Equipos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gestionar_Equipos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gestionar_Equipos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gestionar_Equipos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane Scroll_equipos;
    private javax.swing.JToggleButton buscar;
    private javax.swing.JComboBox<String> combo_status;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTable table_equipos;
    private javax.swing.JLabel wlp;
    // End of variables declaration//GEN-END:variables


public void ObtenerMetodos(){
table_equipos.addMouseListener(new MouseAdapter(){ 
    @Override
    public void mouseClicked(MouseEvent e){
        int fila_point= table_equipos.rowAtPoint(e.getPoint());
        int columna_point= 0;
        if( fila_point> -1){
            ID_equipo_update= (int) model.getValueAt(fila_point, columna_point);
                   
        Informacion_equipo_tecnico iet= new Informacion_equipo_tecnico();
        iet.setVisible(true);
        
        }
    }
    } );
}
}
