
package ventanas;
import java.sql.*;
import clases.Conexion;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;
public class Gestionar_Clientes extends javax.swing.JFrame {
    String user;
    public static int ID_cliente_update = 0;// usamos para comunicar
    DefaultTableModel model = new DefaultTableModel();

    
    public Gestionar_Clientes() {
        initComponents();
        user = Login.user;
        setSize(501, 450);
        setResizable(false);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Atencion al publico- sesion de " + user);
   try{
       Connection cn =Conexion.conectar();
       PreparedStatement pst = cn.prepareStatement(
       "select ID_cliente, nomblre_cliente, mail_cliente, tel_cliente, dir_cliente, ultima_modificacion from clientes");
      ResultSet rs = pst.executeQuery();
      jTable_clientes = new JTable(model);
      jScrollPane1.setViewportView(jTable_clientes) ;
      
      model.addColumn("");
      model.addColumn("nombre");
      model.addColumn("mail");
      model.addColumn("telefono");
      model.addColumn("direccion");
    
      
      while(rs.next()){
          Object [] fila = new Object [5];
          for ( int i = 0 ; i<5; i++){
              fila[i]= rs.getObject(i+1); 
              
          }
          model.addRow(fila);
          
      }
      
      cn.close();
       
   }catch(SQLException e ){
       System.err.println("error en llenado" + e);
       JOptionPane.showMessageDialog( null, " error, contacte" );
       
       
   }
    
    //eventos para el click
    jTable_clientes.addMouseListener(new MouseAdapter(){ 
    @Override
    public void mouseClicked(MouseEvent e){
        int fila_point= jTable_clientes.rowAtPoint(e.getPoint());
        int columna_point= 0;
        if( fila_point> -1){
            ID_cliente_update= (int) model.getValueAt(fila_point, columna_point);
                   JOptionPane.showMessageDialog( null, " elID del cliente es " + ID_cliente_update );
        Informacion_Clientes ic = new Informacion_Clientes();
        
        ic.setVisible(true);
        }
        
    }
    } );
    
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_clientes = new javax.swing.JTable();
        wlp = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(500, 450));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Gestionar Clientes");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 130, -1));

        jTable_clientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable_clientes);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, 200));

        wlp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/wp-1.jpg"))); // NOI18N
        getContentPane().add(wlp, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gestionar_Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gestionar_Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gestionar_Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gestionar_Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gestionar_Clientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_clientes;
    private javax.swing.JLabel wlp;
    // End of variables declaration//GEN-END:variables
}
