/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import java.awt.Toolkit;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import java.sql.*;
import clases.Conexion;
import javax.swing.JOptionPane;
/**
 *
 * @author Ernesto
 */
public class Login extends javax.swing.JFrame {

    public static String user = "";
    String pass = "";
    
    
    
    
    
    public Login() {
        initComponents();
        setSize(400,550);
        setResizable(false);
        setTitle("Acceso al sistema");
        setLocationRelativeTo(null);
        
        ImageIcon wallpaper = new ImageIcon("src/images/wp-1.jpg");
        Icon icono = new ImageIcon(wallpaper.getImage().getScaledInstance(jlabel_fondo.getWidth(), 
                jlabel_fondo.getHeight(), Image.SCALE_DEFAULT));
        jlabel_fondo.setIcon(icono);
        this.repaint();
        
        
       
       
       ImageIcon wallpaper_logo1 = new ImageIcon("src/images/DI.png");
        Icon icono_logo = new ImageIcon(wallpaper_logo1.getImage().getScaledInstance(jLabel1_Logo.getWidth(), 
                jLabel1_Logo.getHeight(), Image.SCALE_DEFAULT));
        jLabel1_Logo.setIcon(icono_logo);
        this.repaint();
        
       
    }

    
    @Override
    public Image getIconImage(){
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/icon.png"));
        return retValue;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_user = new javax.swing.JTextField();
        Acceder = new javax.swing.JButton();
        txt_pasword = new javax.swing.JPasswordField();
        jLabel1_Logo = new javax.swing.JLabel();
        jlabel_fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_user.setBackground(new java.awt.Color(153, 153, 255));
        txt_user.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txt_user.setForeground(new java.awt.Color(255, 255, 255));
        txt_user.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_user.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txt_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 320, 180, -1));

        Acceder.setBackground(new java.awt.Color(102, 102, 255));
        Acceder.setForeground(new java.awt.Color(255, 255, 255));
        Acceder.setText("Acceder");
        Acceder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AccederActionPerformed(evt);
            }
        });
        getContentPane().add(Acceder, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 450, 170, -1));

        txt_pasword.setBackground(new java.awt.Color(153, 153, 255));
        txt_pasword.setForeground(new java.awt.Color(255, 255, 255));
        txt_pasword.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_pasword.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txt_pasword, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 380, 180, 30));
        getContentPane().add(jLabel1_Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 230, 100));
        getContentPane().add(jlabel_fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AccederActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AccederActionPerformed
        // TODO add your handling code here:
        
        
        user = txt_user.getText().trim();
        pass = txt_pasword.getText().trim();
        if(!user.equals("")|| !pass.equals("")){
            try{
                
                Connection cn  = Conexion.conectar();
                PreparedStatement pst = cn.prepareStatement(
                        "select tipo_nivel, estatus from usuarios where username = '"+ user
                +"' and password = '"+ pass + "'");
                
                
                ResultSet rs = pst.executeQuery();
                if(rs.next()){
                    String tipo_nivel = rs.getString("tipo_nivel");
                    String estatus = rs.getString("estatus");
                    if(tipo_nivel.equals("Administrador")&& estatus.equalsIgnoreCase("Activo")){
                    dispose();
                    new Administrador().setVisible(true);
                        
                    }else if(tipo_nivel.equals("Atencion")&& estatus.equalsIgnoreCase("Activo")){
                         dispose();
                    new Capturista().setVisible(true);
                    }else if(tipo_nivel.equals("Tecnico")&& estatus.equalsIgnoreCase("Activo")){
                         dispose();
                    new Tecnico().setVisible(true);
                    }
                    
                }else{
                    JOptionPane.showMessageDialog(null, "datos de acceso incorrecto.");
                    txt_user.setText("");
                    txt_pasword.setText("");
                    
                }
                
                
            }catch(SQLException e ){
                System.err.println("error en el boton acceder " + e);
                JOptionPane.showMessageDialog(null, "error al iniciar sesion.");
                
            }
            
        }else{
            JOptionPane.showMessageDialog(null, "error, hay campos incompletos.");
            
        }
    }//GEN-LAST:event_AccederActionPerformed

    
    public static void main(String args[]) {
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Acceder;
    private javax.swing.JLabel jLabel1_Logo;
    private javax.swing.JLabel jlabel_fondo;
    private javax.swing.JPasswordField txt_pasword;
    private javax.swing.JTextField txt_user;
    // End of variables declaration//GEN-END:variables
}
